# Here cluster SCE depends on network SCE
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-sce
  namespace: default
spec:
  dependsOn:
    - name: network-sce
  valuesFrom:
    - kind: ConfigMap
      name: userinput-configmap
      valuesKey: values.yaml
  interval: 15m
  timeout: 40m
  chart:
    spec:
      chart: components/cluster-sce
      version: '6.5.*'
      sourceRef:
        kind: GitRepository
        name: ack-git
      interval: 5m
  releaseName: cluster-sce-release
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true

---
# Other SCE part of the same clusterproduct can be defined here and the dependency between these SCE
# can be managed using the dependsOn field as shown above.
