apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # A clear, descriptive name for the role
  name: tf-tester-role
rules:
- apiGroups:
  - "infra.contrib.fluxcd.io" # Matches your Terraform CRD's API group
  resources:
  - "terraforms"              # The resource kind
  - "terraforms/status"       # It's good practice to explicitly include the status subresource
  verbs:
  - "get"                     # The specific permissions needed by 'kubectl wait'
  - "list"
  - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # A clear, descriptive name for the binding
  name: tf-tester-binding
roleRef:
  # This points to the ClusterRole we just defined above
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-tester-role
subjects:
  # This is the user (or in this case, ServiceAccount) getting the permissions
- kind: ServiceAccount
  # The name of the ServiceAccount you created
  name: tf-runner-tester
  # The namespace where that ServiceAccount exists
  namespace: default
