apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: {{ .Values.cluster_name }}
  namespace: default
spec:
  # Reconcile cadence: plan/apply and drift detection cadence
  interval: 5m

  # Automate plan approval + apply (good for non-prod; for prod consider manual)
  approvePlan: auto

  # Path within the GitRepository that contains your Terraform code
  path: components/cluster-sce/terraform/cluster

  # Reference to the Flux Source
  sourceRef:
    kind: GitRepository
    name: cloudnative-git

  # Runner configuration (multi-tenancy model)
  serviceAccountName: tf-runner-sa
  destroyResourcesOnDeletion: true

  lock:
    force: true
  
  # New: write all outputs to a Secret
  writeOutputsToSecret:
    name: {{ .Values.cluster_name }}-outputs
    # (optional) add labels/annotations if another controller consumes the secret
    labels:
      app.kubernetes.io/managed-by: tofu-controller
    annotations:
      example.com/expires-at: "never"

  # Terraform variables (match your variables.tf)
  vars:
    - name: cluster_name
      value: {{ .Values.cluster_name }}

  varsFrom:
    - kind: Secret
      name: {{ .Values.network_name }}-outputs

---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: {{ .Values.cluster_name }}-tf-token-writer
  namespace: default # Or your Flux namespace
spec:
  destroyResourcesOnDeletion: true
  
  lock:
    force: true

  # This is the most critical part. It tells Flux to wait until
  # the first stage is successfully applied.
  dependsOn:
    - name: {{ .Values.cluster_name }}

  # Reconcile cadence: plan/apply and drift detection cadence
  interval: 5m

  # Automate plan approval + apply (good for non-prod; for prod consider manual)
  approvePlan: auto

  # Path within the GitRepository that contains your Terraform code
  path: components/cluster-sce/terraform/token-writer
  runnerPodTemplate:
    spec:
      image: 810918108393.dkr.ecr.eu-south-1.amazonaws.com/tf-runner-tools:v1

  # Reference to the Flux Source
  sourceRef:
    kind: GitRepository
    name: cloudnative-git

  # Runner configuration (multi-tenancy model)
  serviceAccountName: tf-runner-sa

  # Define all your variables for this stage here
  vars:
    - name: region
      value: "eu-south-1"
    - name: eks_cluster_name
      value: "{{ .Values.cluster_name }}"
    - name: runner_principal_arn
      value: "arn:aws:iam::810918108393:role/eksctl-k8-simulation-nodegroup-def-NodeInstanceRole-WrSOfoyc7m3b"
    - name: remote_target_namespace
      value: "default"
    - name: publish_secret_namespace
      value: "default"

---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: {{ .Values.cluster_name }}-tf-kubeconfig-builder
  namespace: default # Or your Flux namespace
spec:
  destroyResourcesOnDeletion: true

  lock:
    force: true

  # This is the most critical part. It tells Flux to wait until
  # the first stage is successfully applied.
  dependsOn:
    - name: {{ .Values.cluster_name }}-tf-token-writer
  
  # Reconcile cadence: plan/apply and drift detection cadence
  interval: 5m

  # Automate plan approval + apply (good for non-prod; for prod consider manual)
  approvePlan: auto

  # Path within the GitRepository that contains your Terraform code
  path: components/cluster-sce/terraform/kubeconfig-builder
  runnerPodTemplate:
    spec:
      image: 810918108393.dkr.ecr.eu-south-1.amazonaws.com/tf-runner-tools:v1

  # Reference to the Flux Source
  sourceRef:
    kind: GitRepository
    name: cloudnative-git

  # Runner configuration (multi-tenancy model)
  serviceAccountName: tf-runner-sa

  # Define variables for this stage
  vars:
    - name: publish_secret_namespace
      value: "default"
    - name: publish_secret_name
      value: "{{ .Values.cluster_name }}-remote-kubeconfig-secret" # The final secret for your HelmRelease


