apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-readiness-test"
  namespace: {{ .Release.Namespace }}
  annotations:
    # This hook only runs on 'helm test' (after install/upgrade)
    "helm.sh/hook": test
    # Delete this Job if the test succeeds. Leave it for debugging if it fails.
    "helm.sh/hook-delete-policy": hook-succeeded
    # A weight to control execution order if you have multiple tests
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      serviceAccountName: tf-runner-tester
      restartPolicy: Never
      containers:
        - name: checker
          image: bitnami/kubectl:latest
          command:
            - "/bin/sh"
            - "-c"
            - |
              TF_RESOURCE_NAME="{{ .Values.network_name }}"
              RELEASE_NAMESPACE="{{ .Release.Namespace }}"

              echo "--- TEST hook started. Waiting for Terraform resource '${TF_RESOURCE_NAME}' to become Ready... ---"

              # The single responsibility of this hook: wait for the 'Ready' condition.
              kubectl wait --for=condition=Ready "terraform/${TF_RESOURCE_NAME}" --timeout=45m -n "${RELEASE_NAMESPACE}"

              if [ $? -eq 0 ]; then
                echo "--- Terraform resource is Ready! Test successful. ---"
                exit 0
              else
                echo "--- Timed out waiting for Terraform resource to become Ready. Test failed. ---"
                echo "--- Current status of Terraform resource '${TF_RESOURCE_NAME}': ---"
                kubectl get terraform "${TF_RESOURCE_NAME}" -n "${RELEASE_NAMESPACE}" -o yaml
                exit 1
              fi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-delete-monitor"
  namespace: {{ .Release.Namespace }}
  annotations:
    # This hook only runs after 'helm uninstall' has deleted the main resources
    "helm.sh/hook": post-delete
    # Always clean up this Job, regardless of outcome, to not block uninstallation.
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
    # A weight to control execution order
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      serviceAccountName: tf-runner-tester
      restartPolicy: Never
      containers:
        - name: monitor
          image: bitnami/kubectl:latest
          command:
            - "/bin/sh"
            - "-c"
            - |
              TF_RESOURCE_NAME="{{ .Values.network_name }}"
              RELEASE_NAMESPACE="{{ .Release.Namespace }}"

              echo "--- POST-DELETE hook started. Waiting for Terraform resource '${TF_RESOURCE_NAME}' to be fully deleted... ---"

              # The single responsibility of this hook: wait for the resource to be deleted.
              kubectl wait --for=delete "terraform/${TF_RESOURCE_NAME}" --timeout=45m -n "${RELEASE_NAMESPACE}"

              if [ $? -eq 0 ]; then
                echo "--- Terraform resource successfully deleted. Post-delete hook successful. ---"
                exit 0
              else
                echo "--- Timed out waiting for Terraform resource deletion. Post-delete hook failed. ---"
                exit 1
              fi
