---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-readiness-test"
  namespace: {{ .Release.Namespace }}
  annotations:
    # This marks the resource as a Helm Test
    "helm.sh/hook": test
    # This tells Helm to delete this pod after a successful test run.
    # If the test fails, the pod is left for debugging.
    "helm.sh/hook-delete-policy": hook-completed,before-hook-creation
spec:
  # --- THIS IS THE KEY CHANGE ---
  # Instead of creating a new ServiceAccount, we use the existing one
  # that the main Terraform resource already uses.
  serviceAccountName: tf-runner-tester # IMPORTANT: Assumes tf-runner-tester is in the same namespace

  # We don't want this test pod hanging around forever.
  restartPolicy: Never
  
  containers:
    - name: checker
      # Using a small, official image that contains the kubectl binary
      image: bitnami/kubectl:latest
      command:
        - "/bin/sh"
        - "-c"
        - |
          echo "--- Waiting for HelmRelease 'helmrelease/bsdeployment-sce' to become Ready ---"
          
          # This is the core of the test.
          # It waits up to 45 minutes (--timeout=45m) for the 'Ready' condition on the HelmRelease resource.
          # If the condition is met, the command exits with code 0 (Success).
          # If it times out or fails, it exits with code 1 (Failure).
          kubectl wait --for=condition=Ready helmrelease/bsdeployment-sce --timeout=45m -n {{ .Release.Namespace }}
          
          if [ $? -eq 0 ]; then
            echo "--- HelmRelease resource is Ready! Test successful. ---"
            exit 0
          else
            echo "--- Timed out waiting for HelmRelease resource. Test failed. ---"
            echo "--- Current status of HelmRelease resource 'bsdeployment-sce': ---"
            kubectl get helmrelease bsdeployment-sce -n {{ .Release.Namespace }} -o yaml
            exit 1
          fi
