---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bsinfra-sce
  namespace: default
spec:
  dependsOn:
    - name: cluster-sce
  values:
    bucket_name: {{ .Values.bucket_name }}
    bsinfra_name: {{ .Values.bsinfra_name }}
  interval: 15m
  timeout: 40m
  chart:
    spec:
      chart: components/backing-service-infra-sce
      version: '6.5.*'
      sourceRef:
        kind: GitRepository
        name: cloudnative-git
      interval: 5m
  releaseName: bsinfra-sce-release
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bsdeployment-sce
  namespace: default
spec:
  dependsOn:
    - name: bsinfra-sce
    - name: cluster-sce
  valuesFrom:
    - kind: Secret
      name: {{ .Values.bsinfra_name }}-outputs 
      valuesKey: s3_bucket_arn
      targetPath: bucket_name
    - kind: Secret
      name: {{ .Values.cluster_name }}-outputs 
      valuesKey: cluster_endpoint
      targetPath: cluster_endpoint
    
  interval: 15m
  timeout: 40m
  chart:
    spec:
      chart: components/backing-service-deployment-sce
      version: '6.5.*'
      sourceRef:
        kind: GitRepository
        name: cloudnative-git
      interval: 5m
  releaseName: {{ .Values.bs_deployment_sce_helmrelease }}
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  kubeConfig:
    secretRef:
      name: {{ .Values.kube_config_name }}

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sync-fieldexport-sce # This is a temporary workaoround for POC until we have native support via some custom resource.
  namespace: default
spec:
  dependsOn:
    - name: bsdeployment-sce
  values:
    name: {{ .Values.name }}
    kube_config_name: {{ .Values.kube_config_name }}
    helm_release_name: {{ .Values.bs_deployment_sce_helmrelease }}
    config_map_name: {{ .Values.bs_deployment_sce_helmrelease }}-outputs
    
  interval: 15m
  timeout: 40m
  chart:
    spec:
      chart: components/helm-field-export-sce
      version: '6.5.*'
      sourceRef:
        kind: GitRepository
        name: cloudnative-git
      interval: 5m
  releaseName: sync-fieldexport-sce-release
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true