---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bsinfra-sce
  namespace: default
spec:
  dependsOn:
    - name: cluster-sce
  values:
    bucket_name: {{ .Values.bucket_name }}
    bsinfra_name: {{ .Values.bsinfra_name }}
  interval: 15m
  timeout: 40m
  chart:
    spec:
      chart: components/backing-service-infra-sce
      version: '6.5.*'
      sourceRef:
        kind: GitRepository
        name: cloudnative-git
      interval: 5m
  releaseName: bsinfra-sce-release
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bsdeployment-sce
  namespace: default
spec:
  dependsOn:
    - name: bsinfra-sce
  valuesFrom:
    - kind: Secret
      name: {{ .Values.bsinfra_name }}-outputs 
      valuesKey: s3_bucket_arn
  interval: 15m
  timeout: 40m
  chart:
    spec:
      chart: components/backing-service-deployment-sce
      version: '6.5.*'
      sourceRef:
        kind: GitRepository
        name: cloudnative-git
      interval: 5m
  releaseName: bsdeployment-sce-release
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true